name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git -b master
          echo "${HOME}/flutter/bin" >> $GITHUB_PATH
          echo "FLUTTER_HOME=${HOME}/flutter" >> $GITHUB_ENV
        
      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Run tests
        run: ./tool/travis.sh
