name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone Flutter repository with master channel
        uses: actions/checkout@v2
        with:
          repository: 'flutter/flutter'
          ref: 'master'
          path: 'flutter'
          fetch-depth: 0

      - name: Add Flutter to the PATH
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          
      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Run tests
        run: ./tool/travis.sh
