name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git -b master
          export PATH=$PATH:$(pwd)/flutter/bin
          export FLUTTER_HOME=$(pwd)/flutter
        
      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Run tests
        run: ./tool/travis.sh
